### Doing things with tensors

In [23]:
import torch
from torch import Tensor
import numpy as np
import time

In [29]:
%timeit -n100 3*3

24.5 ns ± 2.33 ns per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
def blah():
    return 3

In [32]:
# %load -n blah
def blah():
    return 3

In [33]:
x = tensor([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [34]:
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [35]:
x.shape

torch.Size([4, 3])

In [36]:
x/2

tensor([[0, 0, 1],
        [1, 2, 2],
        [3, 3, 4],
        [4, 5, 5]])

In [38]:
x.type()

'torch.LongTensor'

In [41]:
x.add_(4)

tensor([[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])

In [43]:
x.float()/2

tensor([[2.0000, 2.5000, 3.0000],
        [3.5000, 4.0000, 4.5000],
        [5.0000, 5.5000, 6.0000],
        [6.5000, 7.0000, 7.5000]])

In [51]:
x = tensor([[0.,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [52]:
x.div_(2)

tensor([[0.0000, 0.5000, 1.0000],
        [1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000],
        [4.5000, 5.0000, 5.5000]])

In [53]:
x

tensor([[0.0000, 0.5000, 1.0000],
        [1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000],
        [4.5000, 5.0000, 5.5000]])

In [54]:
x.int()

tensor([[0, 0, 1],
        [1, 2, 2],
        [3, 3, 4],
        [4, 5, 5]], dtype=torch.int32)

In [57]:
8%2

0

In [48]:
x+x

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.],
        [18., 20., 22.]])

In [58]:
x

tensor([[0.0000, 0.5000, 1.0000],
        [1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000],
        [4.5000, 5.0000, 5.5000]])

In [60]:
x.transpose(0,1)

tensor([[0.0000, 1.5000, 3.0000, 4.5000],
        [0.5000, 2.0000, 3.5000, 5.0000],
        [1.0000, 2.5000, 4.0000, 5.5000]])

In [63]:
y = x.permute([1,0])
y

tensor([[0.0000, 1.5000, 3.0000, 4.5000],
        [0.5000, 2.0000, 3.5000, 5.0000],
        [1.0000, 2.5000, 4.0000, 5.5000]])

In [64]:
y.shape

torch.Size([3, 4])

In [73]:
np.matmul(x.numpy(), y.numpy())

array([[ 1.25,  3.5 ,  5.75,  8.  ],
       [ 3.5 , 12.5 , 21.5 , 30.5 ],
       [ 5.75, 21.5 , 37.25, 53.  ],
       [ 8.  , 30.5 , 53.  , 75.5 ]], dtype=float32)

In [65]:
x_mult_y = x@y
x_mult_y

tensor([[ 1.2500,  3.5000,  5.7500,  8.0000],
        [ 3.5000, 12.5000, 21.5000, 30.5000],
        [ 5.7500, 21.5000, 37.2500, 53.0000],
        [ 8.0000, 30.5000, 53.0000, 75.5000]])

In [66]:
x_mult_y.shape

torch.Size([4, 4])

In [74]:
y_mult_x = y@x
y_mult_x

tensor([[31.5000, 36.0000, 40.5000],
        [36.0000, 41.5000, 47.0000],
        [40.5000, 47.0000, 53.5000]])

In [75]:
y_mult_x.shape

torch.Size([3, 3])

In [77]:
torch.log(x), torch.exp(x), torch.sin(x), torch.sigmoid(x), torch.relu(x)

(tensor([[   -inf, -0.6931,  0.0000],
         [ 0.4055,  0.6931,  0.9163],
         [ 1.0986,  1.2528,  1.3863],
         [ 1.5041,  1.6094,  1.7047]]), tensor([[  1.0000,   1.6487,   2.7183],
         [  4.4817,   7.3891,  12.1825],
         [ 20.0855,  33.1155,  54.5982],
         [ 90.0171, 148.4132, 244.6919]]), tensor([[ 0.0000,  0.4794,  0.8415],
         [ 0.9975,  0.9093,  0.5985],
         [ 0.1411, -0.3508, -0.7568],
         [-0.9775, -0.9589, -0.7055]]), tensor([[0.5000, 0.6225, 0.7311],
         [0.8176, 0.8808, 0.9241],
         [0.9526, 0.9707, 0.9820],
         [0.9890, 0.9933, 0.9959]]), tensor([[0.0000, 0.5000, 1.0000],
         [1.5000, 2.0000, 2.5000],
         [3.0000, 3.5000, 4.0000],
         [4.5000, 5.0000, 5.5000]]))

### Broadcasting

In [78]:
.1*x

tensor([[0.0000, 0.0500, 0.1000],
        [0.1500, 0.2000, 0.2500],
        [0.3000, 0.3500, 0.4000],
        [0.4500, 0.5000, 0.5500]])

In [80]:
x

tensor([[0.0000, 0.5000, 1.0000],
        [1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000],
        [4.5000, 5.0000, 5.5000]])

In [79]:
a = tensor([1.,2,3])
a*x

tensor([[ 0.0000,  1.0000,  3.0000],
        [ 1.5000,  4.0000,  7.5000],
        [ 3.0000,  7.0000, 12.0000],
        [ 4.5000, 10.0000, 16.5000]])

In [81]:
a = tensor([1.,2,3])
a+x

tensor([[1.0000, 2.5000, 4.0000],
        [2.5000, 4.0000, 5.5000],
        [4.0000, 5.5000, 7.0000],
        [5.5000, 7.0000, 8.5000]])

In [111]:
a = tensor([1.,2,3,4])

In [117]:
def plusone(x):
    return x+1

In [119]:
x=2
plusone(plusone(x))

4

In [115]:
a.view([2,2,1,1,1,1])

tensor([[[[[[1.]]]],



         [[[[2.]]]]],




        [[[[[3.]]]],



         [[[[4.]]]]]])

In [120]:
a = tensor([1.,2,3,4]).transpose(0,1)
a*x

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [121]:
a = tensor([[1.],[2],[3],[4]])
a*x

tensor([[2.],
        [4.],
        [6.],
        [8.]])

### Higher dimensions

In [122]:
z = tensor([[[0,1],   [2,3],   [4,5]] , 
            [[6,7],   [8,9],   [10,11]],
            [[12,13], [14,15], [16,17]],
            [[18,19], [20,21], [22,23]]])
z

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

In [125]:
z[2,2,0].item()

16

In [123]:
z.shape

torch.Size([4, 3, 2])

### Other ways of creating tensors

In [ ]:
torch.zeros([4,3,2])

In [126]:
t = torch.ones([4,3,2])
t

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [127]:
torch.zero_(t)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [128]:
t

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [129]:
torch.rand([3,2])

tensor([[0.7966, 0.1086],
        [0.1459, 0.3640],
        [0.0868, 0.6395]])

In [130]:
torch.randint(low=-100,high=100,size=[3,2])

tensor([[ 35,  30],
        [-83,  55],
        [ 34,  60]])

In [134]:
torch.arange(-1,3)

tensor([-1,  0,  1,  2])

### tensor aggregate functions

In [146]:
t = torch.randn([100,90])

In [152]:
t[0].shape

torch.Size([90])

In [148]:
t.mean(), t.std()

(tensor(0.0004), tensor(1.0188))

In [150]:
s = t.sum(dim=1), s.shape

NameError: name 's' is not defined

### Type conversions

In [153]:
t = torch.randint(low=-100,high=100,size=[3,2])

In [154]:
t.type()

'torch.LongTensor'

In [155]:
s = t.float()
s

tensor([[  60.,  -35.],
        [  10.,   62.],
        [-100.,    2.]])

In [156]:
s.type()

'torch.FloatTensor'

### Indexing into tensors

In [157]:
t = torch.arange(10,20)
t

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [159]:
t[5], t[-10]

(tensor(15), tensor(10))

In [ ]:
t[1:5], t[2:-6]

In [160]:
t[1:10:2]

tensor([11, 13, 15, 17, 19])

In [161]:
t=torch.rand([3,5,7])
t

tensor([[[0.0288, 0.0500, 0.1142, 0.9138, 0.1082, 0.3222, 0.1583],
         [0.7317, 0.2657, 0.6159, 0.8606, 0.6528, 0.3690, 0.7610],
         [0.9027, 0.7790, 0.6025, 0.2781, 0.0944, 0.2305, 0.1952],
         [0.4656, 0.0901, 0.7071, 0.7479, 0.7888, 0.2469, 0.0907],
         [0.3020, 0.4229, 0.4681, 0.0824, 0.9474, 0.6842, 0.5128]],

        [[0.2637, 0.9011, 0.8334, 0.0622, 0.8402, 0.2161, 0.4145],
         [0.4903, 0.8792, 0.9352, 0.8633, 0.0183, 0.4092, 0.9999],
         [0.7453, 0.8375, 0.6636, 0.5619, 0.0780, 0.2794, 0.4700],
         [0.4960, 0.9630, 0.1690, 0.5717, 0.0663, 0.6168, 0.5690],
         [0.5501, 0.5330, 0.4322, 0.0919, 0.7178, 0.5930, 0.1581]],

        [[0.2174, 0.0852, 0.7249, 0.9846, 0.4938, 0.1179, 0.5171],
         [0.5222, 0.0501, 0.2560, 0.6578, 0.0301, 0.3149, 0.9653],
         [0.7582, 0.2545, 0.4510, 0.0397, 0.4795, 0.1724, 0.9974],
         [0.5616, 0.5022, 0.9141, 0.8398, 0.7424, 0.9954, 0.9485],
         [0.9892, 0.6919, 0.1675, 0.3668, 0.6479, 0.3866, 

In [163]:
t[0,0,0], t[0,0,0].item()

(tensor(0.0288), 0.02878624200820923)

In [164]:
t[0,0,:], t[0,0,:].shape

(tensor([0.0288, 0.0500, 0.1142, 0.9138, 0.1082, 0.3222, 0.1583]),
 torch.Size([7]))

In [165]:
t[0,:,0], t[0,:,0].shape

(tensor([0.0288, 0.7317, 0.9027, 0.4656, 0.3020]), torch.Size([5]))

In [166]:
t[:,0,0], t[:,0,0].shape

(tensor([0.0288, 0.2637, 0.2174]), torch.Size([3]))

In [167]:
t[1,:,:], t[1,:,:].shape

(tensor([[0.2637, 0.9011, 0.8334, 0.0622, 0.8402, 0.2161, 0.4145],
         [0.4903, 0.8792, 0.9352, 0.8633, 0.0183, 0.4092, 0.9999],
         [0.7453, 0.8375, 0.6636, 0.5619, 0.0780, 0.2794, 0.4700],
         [0.4960, 0.9630, 0.1690, 0.5717, 0.0663, 0.6168, 0.5690],
         [0.5501, 0.5330, 0.4322, 0.0919, 0.7178, 0.5930, 0.1581]]),
 torch.Size([5, 7]))

In [168]:
t[1,...]

tensor([[0.2637, 0.9011, 0.8334, 0.0622, 0.8402, 0.2161, 0.4145],
        [0.4903, 0.8792, 0.9352, 0.8633, 0.0183, 0.4092, 0.9999],
        [0.7453, 0.8375, 0.6636, 0.5619, 0.0780, 0.2794, 0.4700],
        [0.4960, 0.9630, 0.1690, 0.5717, 0.0663, 0.6168, 0.5690],
        [0.5501, 0.5330, 0.4322, 0.0919, 0.7178, 0.5930, 0.1581]])

In [169]:
t[1,:,2]

tensor([0.8334, 0.9352, 0.6636, 0.1690, 0.4322])

In [170]:
t

tensor([[[0.0288, 0.0500, 0.1142, 0.9138, 0.1082, 0.3222, 0.1583],
         [0.7317, 0.2657, 0.6159, 0.8606, 0.6528, 0.3690, 0.7610],
         [0.9027, 0.7790, 0.6025, 0.2781, 0.0944, 0.2305, 0.1952],
         [0.4656, 0.0901, 0.7071, 0.7479, 0.7888, 0.2469, 0.0907],
         [0.3020, 0.4229, 0.4681, 0.0824, 0.9474, 0.6842, 0.5128]],

        [[0.2637, 0.9011, 0.8334, 0.0622, 0.8402, 0.2161, 0.4145],
         [0.4903, 0.8792, 0.9352, 0.8633, 0.0183, 0.4092, 0.9999],
         [0.7453, 0.8375, 0.6636, 0.5619, 0.0780, 0.2794, 0.4700],
         [0.4960, 0.9630, 0.1690, 0.5717, 0.0663, 0.6168, 0.5690],
         [0.5501, 0.5330, 0.4322, 0.0919, 0.7178, 0.5930, 0.1581]],

        [[0.2174, 0.0852, 0.7249, 0.9846, 0.4938, 0.1179, 0.5171],
         [0.5222, 0.0501, 0.2560, 0.6578, 0.0301, 0.3149, 0.9653],
         [0.7582, 0.2545, 0.4510, 0.0397, 0.4795, 0.1724, 0.9974],
         [0.5616, 0.5022, 0.9141, 0.8398, 0.7424, 0.9954, 0.9485],
         [0.9892, 0.6919, 0.1675, 0.3668, 0.6479, 0.3866, 

In [171]:
t[0,0:4,1:3]

tensor([[0.0500, 0.1142],
        [0.2657, 0.6159],
        [0.7790, 0.6025],
        [0.0901, 0.7071]])

### Manipulating tensor shape

In [180]:
t = torch.rand([1,2,1,3])
t

tensor([[[[0.5131, 0.4611, 0.7983]],

         [[0.4094, 0.6442, 0.4676]]]])

In [184]:
s= t.squeeze()
s

tensor([[0.5131, 0.4611, 0.7983],
        [0.4094, 0.6442, 0.4676]])

In [ ]:
s.unsqueeze(dim=0)

In [191]:
s[:,None,None,None,:,None].shape

torch.Size([2, 1, 1, 1, 3, 1])

In [193]:
a = torch.rand([4,3])
a

tensor([[0.4956, 0.0920, 0.5274],
        [0.1415, 0.4804, 0.9717],
        [0.7062, 0.8672, 0.8646],
        [0.7354, 0.9060, 0.7250]])

In [198]:
v = Tensor([1.,2,3,4])
v = v[...,None]#[None,...]
v

tensor([1., 2., 3., 4.])

In [202]:
a*v[..., None]

tensor([[0.4956, 0.0920, 0.5274],
        [0.2830, 0.9608, 1.9433],
        [2.1186, 2.6017, 2.5938],
        [2.9417, 3.6240, 2.9002]])

In [175]:
t = torch.arange(10)
t.shape

torch.Size([10])

In [176]:
t.unsqueeze(dim=0).shape

torch.Size([1, 10])

In [179]:
t.unsqueeze(dim=1)

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
t.unsqueeze_(dim=0)

In [ ]:
t.shape

In [ ]:
t.squeeze_()

In [ ]:
t.shape

In [ ]:
t = torch.randn([4,3])

In [ ]:
t, t.shape

In [ ]:
t[:,None,None,:], t[:,None,None,:].shape

In [ ]:
t.permute([1,0]), t.shape, t.permute([1,0]).shape

In [ ]:
t.view([3,4])

In [ ]:
t.view([3*4])

In [ ]:
t.view([2,6])

In [ ]:
t.view([6,2])

### Combining tensors

In [203]:
x = tensor([1,2,3])
y = tensor([4,5,6])

x2 = torch.rand([2,2])
y2 = torch.rand([2,3])

In [204]:
torch.cat([x,y])

tensor([1, 2, 3, 4, 5, 6])

In [205]:
torch.cat([x2,y2])

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 2 and 3 in dimension 1 at /Users/distiller/project/conda/conda-bld/pytorch-nightly_1554268387286/work/aten/src/TH/generic/THTensor.cpp:721

In [206]:
torch.cat([x2,y2],dim=1)

tensor([[0.1913, 0.7914, 0.8149, 0.9612, 0.9116],
        [0.4410, 0.5844, 0.6833, 0.4420, 0.2464]])

In [207]:
torch.cat([x2,x2,x2]), torch.cat([x2,x2,x2]).shape

(tensor([[0.1913, 0.7914],
         [0.4410, 0.5844],
         [0.1913, 0.7914],
         [0.4410, 0.5844],
         [0.1913, 0.7914],
         [0.4410, 0.5844]]), torch.Size([6, 2]))

In [208]:
torch.stack([x2,x2,x2]), torch.stack([x2,x2,x2]).shape

(tensor([[[0.1913, 0.7914],
          [0.4410, 0.5844]],
 
         [[0.1913, 0.7914],
          [0.4410, 0.5844]],
 
         [[0.1913, 0.7914],
          [0.4410, 0.5844]]]), torch.Size([3, 2, 2]))

### Interoperating with numpy

In [ ]:
t.numpy()

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
tensor(a)

### Moving objects between devices

In [209]:
t.device

device(type='cpu')

In [ ]:
t.cuda()

In [ ]:
t.device