### Doing things with tensors

In [246]:
import torch
from torch import tensor
import numpy as np

In [226]:
x = tensor([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [227]:
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [228]:
x.shape

torch.Size([4, 3])

In [229]:
x/2

tensor([[0, 0, 1],
        [1, 2, 2],
        [3, 3, 4],
        [4, 5, 5]])

In [230]:
x.float()/2

tensor([[0.0000, 0.5000, 1.0000],
        [1.5000, 2.0000, 2.5000],
        [3.0000, 3.5000, 4.0000],
        [4.5000, 5.0000, 5.5000]])

In [231]:
x = tensor([[0.,1,2],[3,4,5],[6,7,8],[9,10,11]])

In [232]:
x+x

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.],
        [18., 20., 22.]])

In [233]:
y = x.permute([1,0])
y

tensor([[ 0.,  3.,  6.,  9.],
        [ 1.,  4.,  7., 10.],
        [ 2.,  5.,  8., 11.]])

In [234]:
y.shape

torch.Size([3, 4])

In [235]:
x_mult_y = x@y
x_mult_y

tensor([[  5.,  14.,  23.,  32.],
        [ 14.,  50.,  86., 122.],
        [ 23.,  86., 149., 212.],
        [ 32., 122., 212., 302.]])

In [236]:
x_mult_y.shape

torch.Size([4, 4])

In [237]:
y_mult_x = y@x
y_mult_x

tensor([[126., 144., 162.],
        [144., 166., 188.],
        [162., 188., 214.]])

In [238]:
y_mult_x.shape

torch.Size([3, 3])

In [244]:
torch.log(x), torch.exp(x), torch.sin(x), torch.sigmoid(x)

(tensor([[  -inf, 0.0000, 0.6931],
         [1.0986, 1.3863, 1.6094],
         [1.7918, 1.9459, 2.0794],
         [2.1972, 2.3026, 2.3979]]),
 tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00],
         [2.0086e+01, 5.4598e+01, 1.4841e+02],
         [4.0343e+02, 1.0966e+03, 2.9810e+03],
         [8.1031e+03, 2.2026e+04, 5.9874e+04]]),
 tensor([[ 0.0000,  0.8415,  0.9093],
         [ 0.1411, -0.7568, -0.9589],
         [-0.2794,  0.6570,  0.9894],
         [ 0.4121, -0.5440, -1.0000]]),
 tensor([[0.5000, 0.7311, 0.8808],
         [0.9526, 0.9820, 0.9933],
         [0.9975, 0.9991, 0.9997],
         [0.9999, 1.0000, 1.0000]]))

### Broadcasting

In [48]:
.1*x

tensor([[0.0000, 0.1000, 0.2000],
        [0.3000, 0.4000, 0.5000],
        [0.6000, 0.7000, 0.8000],
        [0.9000, 1.0000, 1.1000]])

In [43]:
a = tensor([1.,2,3])
a*x

tensor([[ 0.,  2.,  6.],
        [ 3.,  8., 15.],
        [ 6., 14., 24.],
        [ 9., 20., 33.]])

In [47]:
a = tensor([1.,2,3])
a+x

tensor([[ 1.,  3.,  5.],
        [ 4.,  6.,  8.],
        [ 7.,  9., 11.],
        [10., 12., 14.]])

In [44]:
a = tensor([1,2,3,4])
a*x

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [46]:
a = tensor([[1.],[2],[3],[4]])
a*x

tensor([[ 0.,  1.,  2.],
        [ 6.,  8., 10.],
        [18., 21., 24.],
        [36., 40., 44.]])

### Higher dimensions

In [66]:
z = tensor([[[0,1],   [2,3],   [4,5]] , 
            [[6,7],   [8,9],   [10,11]],
            [[12,13], [14,15], [16,17]],
            [[18,19], [20,21], [22,23]]])
z

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

In [65]:
z.shape

torch.Size([4, 3, 2])

### Other ways of creating tensors

In [68]:
torch.zeros([4,3,2])

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [78]:
t = torch.ones([4,3,2])

In [79]:
torch.zero_(t)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [80]:
t

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [83]:
torch.rand([3,2])

tensor([[0.3639, 0.5287],
        [0.5901, 0.4429],
        [0.5642, 0.6504]])

In [89]:
torch.randint(low=-100,high=100,size=[3,2])

tensor([[ 79, -59],
        [-36,  75],
        [  8,  -4]])

In [95]:
torch.arange(-1,3)

tensor([-1,  0,  1,  2])

### tensor stats

In [119]:
t = torch.randn([10000])

In [120]:
t.mean(), t.std()

(tensor(0.0005), tensor(0.9963))

In [121]:
t.abs().mean()

tensor(0.7924)

### Type conversions

In [122]:
t = torch.randint(low=-100,high=100,size=[3,2])

In [125]:
t.type()

'torch.LongTensor'

In [127]:
s = t.float()
s

tensor([[-90.,  32.],
        [ 14.,  98.],
        [ 57., -97.]])

In [128]:
s.type()

'torch.FloatTensor'

### Indexing into tensors

In [141]:
t = torch.arange(10,20)
t

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [143]:
t[5], t[-3]

(tensor(15), tensor(17))

In [148]:
t[1:5], t[2:-6]

(tensor([11, 12, 13, 14]), tensor([12, 13]))

In [153]:
t=torch.rand([3,5,7])
t

tensor([[[0.2536, 0.7824, 0.5798, 0.6028, 0.8858, 0.5191, 0.3799],
         [0.6237, 0.9484, 0.0085, 0.3907, 0.8634, 0.5675, 0.0504],
         [0.3512, 0.4913, 0.8054, 0.4200, 0.2539, 0.6001, 0.7363],
         [0.1704, 0.5471, 0.7856, 0.6983, 0.5426, 0.0056, 0.4490],
         [0.9767, 0.5996, 0.9224, 0.6416, 0.8763, 0.4306, 0.6668]],

        [[0.9486, 0.0467, 0.3912, 0.5958, 0.4657, 0.3174, 0.0412],
         [0.6532, 0.0774, 0.0200, 0.1260, 0.1127, 0.1653, 0.2532],
         [0.7877, 0.1416, 0.6204, 0.7078, 0.9449, 0.9765, 0.7316],
         [0.9380, 0.6449, 0.0463, 0.8138, 0.7067, 0.4322, 0.4280],
         [0.6393, 0.7893, 0.6722, 0.4198, 0.8115, 0.2552, 0.5892]],

        [[0.3430, 0.1379, 0.6269, 0.7006, 0.5682, 0.8105, 0.7586],
         [0.8499, 0.1285, 0.9013, 0.2523, 0.0946, 0.2984, 0.9573],
         [0.9193, 0.6298, 0.0193, 0.7621, 0.0096, 0.2103, 0.6300],
         [0.2119, 0.1982, 0.3771, 0.0435, 0.5157, 0.7176, 0.2210],
         [0.9863, 0.4598, 0.4599, 0.8042, 0.7350, 0.3428, 

In [155]:
t[0,0,0], t[0,0,0].item()

(tensor(0.2536), 0.2535603642463684)

In [162]:
t[0,0,:], t[0,0,:].shape

(tensor([0.2536, 0.7824, 0.5798, 0.6028, 0.8858, 0.5191, 0.3799]),
 torch.Size([7]))

In [163]:
t[0,:,0], t[0,:,0].shape

(tensor([0.2536, 0.6237, 0.3512, 0.1704, 0.9767]), torch.Size([5]))

In [164]:
t[:,0,0], t[:,0,0].shape

(tensor([0.2536, 0.9486, 0.3430]), torch.Size([3]))

In [168]:
t[1,:,:], t[1,:,:].shape

(tensor([[0.9486, 0.0467, 0.3912, 0.5958, 0.4657, 0.3174, 0.0412],
         [0.6532, 0.0774, 0.0200, 0.1260, 0.1127, 0.1653, 0.2532],
         [0.7877, 0.1416, 0.6204, 0.7078, 0.9449, 0.9765, 0.7316],
         [0.9380, 0.6449, 0.0463, 0.8138, 0.7067, 0.4322, 0.4280],
         [0.6393, 0.7893, 0.6722, 0.4198, 0.8115, 0.2552, 0.5892]]),
 torch.Size([5, 7]))

In [170]:
t[1,...]

tensor([[0.9486, 0.0467, 0.3912, 0.5958, 0.4657, 0.3174, 0.0412],
        [0.6532, 0.0774, 0.0200, 0.1260, 0.1127, 0.1653, 0.2532],
        [0.7877, 0.1416, 0.6204, 0.7078, 0.9449, 0.9765, 0.7316],
        [0.9380, 0.6449, 0.0463, 0.8138, 0.7067, 0.4322, 0.4280],
        [0.6393, 0.7893, 0.6722, 0.4198, 0.8115, 0.2552, 0.5892]])

In [175]:
t[1,:,2]

tensor([0.3912, 0.0200, 0.6204, 0.0463, 0.6722])

In [178]:
t

tensor([[[0.2536, 0.7824, 0.5798, 0.6028, 0.8858, 0.5191, 0.3799],
         [0.6237, 0.9484, 0.0085, 0.3907, 0.8634, 0.5675, 0.0504],
         [0.3512, 0.4913, 0.8054, 0.4200, 0.2539, 0.6001, 0.7363],
         [0.1704, 0.5471, 0.7856, 0.6983, 0.5426, 0.0056, 0.4490],
         [0.9767, 0.5996, 0.9224, 0.6416, 0.8763, 0.4306, 0.6668]],

        [[0.9486, 0.0467, 0.3912, 0.5958, 0.4657, 0.3174, 0.0412],
         [0.6532, 0.0774, 0.0200, 0.1260, 0.1127, 0.1653, 0.2532],
         [0.7877, 0.1416, 0.6204, 0.7078, 0.9449, 0.9765, 0.7316],
         [0.9380, 0.6449, 0.0463, 0.8138, 0.7067, 0.4322, 0.4280],
         [0.6393, 0.7893, 0.6722, 0.4198, 0.8115, 0.2552, 0.5892]],

        [[0.3430, 0.1379, 0.6269, 0.7006, 0.5682, 0.8105, 0.7586],
         [0.8499, 0.1285, 0.9013, 0.2523, 0.0946, 0.2984, 0.9573],
         [0.9193, 0.6298, 0.0193, 0.7621, 0.0096, 0.2103, 0.6300],
         [0.2119, 0.1982, 0.3771, 0.0435, 0.5157, 0.7176, 0.2210],
         [0.9863, 0.4598, 0.4599, 0.8042, 0.7350, 0.3428, 

In [187]:
t[0,0:4,1:3]

tensor([[0.7824, 0.5798],
        [0.9484, 0.0085],
        [0.4913, 0.8054],
        [0.5471, 0.7856]])

### Manipulating tensor shape

In [197]:
t = torch.arange(10)
t.shape

torch.Size([10])

In [198]:
t.unsqueeze_(dim=0)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [199]:
t.shape

torch.Size([1, 10])

In [200]:
t.unsqueeze_(dim=0)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [201]:
t.shape

torch.Size([1, 1, 10])

In [203]:
t.squeeze_()

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
t.shape

torch.Size([10])

In [206]:
t = torch.randn([4,3])

In [210]:
t, t.shape

(tensor([[ 0.3315, -0.0212,  0.4756],
         [ 1.4326, -1.3173, -0.1902],
         [ 1.0904,  0.0874, -0.3069],
         [ 1.6421,  0.7198,  1.0596]]), torch.Size([4, 3]))

In [212]:
t[:,None,None,:], t[:,None,None,:].shape

(tensor([[[[ 0.3315, -0.0212,  0.4756]]],
 
 
         [[[ 1.4326, -1.3173, -0.1902]]],
 
 
         [[[ 1.0904,  0.0874, -0.3069]]],
 
 
         [[[ 1.6421,  0.7198,  1.0596]]]]), torch.Size([4, 1, 1, 3]))

In [216]:
t.permute([1,0]), t.shape, t.permute([1,0]).shape

(tensor([[ 0.3315,  1.4326,  1.0904,  1.6421],
         [-0.0212, -1.3173,  0.0874,  0.7198],
         [ 0.4756, -0.1902, -0.3069,  1.0596]]),
 torch.Size([4, 3]),
 torch.Size([3, 4]))

In [219]:
t.view([3,4])

tensor([[ 0.3315, -0.0212,  0.4756,  1.4326],
        [-1.3173, -0.1902,  1.0904,  0.0874],
        [-0.3069,  1.6421,  0.7198,  1.0596]])

In [220]:
t.view([3*4])

tensor([ 0.3315, -0.0212,  0.4756,  1.4326, -1.3173, -0.1902,  1.0904,  0.0874,
        -0.3069,  1.6421,  0.7198,  1.0596])

In [221]:
t.view([2,6])

tensor([[ 0.3315, -0.0212,  0.4756,  1.4326, -1.3173, -0.1902],
        [ 1.0904,  0.0874, -0.3069,  1.6421,  0.7198,  1.0596]])

In [222]:
t.view([6,2])

tensor([[ 0.3315, -0.0212],
        [ 0.4756,  1.4326],
        [-1.3173, -0.1902],
        [ 1.0904,  0.0874],
        [-0.3069,  1.6421],
        [ 0.7198,  1.0596]])

### Combining tensors

In [278]:
x = tensor([1,2,3])
y = tensor([4,5,6])

x2 = torch.rand([2,2])
y2 = torch.rand([2,3])

In [279]:
torch.cat([x,y])

tensor([1, 2, 3, 4, 5, 6])

In [280]:
torch.cat([x2,y2])

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 2 and 3 in dimension 1 at /Users/distiller/project/conda/conda-bld/pytorch-nightly_1554268387286/work/aten/src/TH/generic/THTensor.cpp:721

In [281]:
torch.cat([x2,y2],dim=1)

tensor([[0.6044, 0.8022, 0.3897, 0.2856, 0.5707],
        [0.3379, 0.6814, 0.2685, 0.9394, 0.3688]])

In [287]:
torch.cat([x2,x2,x2]), torch.cat([x2,x2,x2]).shape

(tensor([[0.6044, 0.8022],
         [0.3379, 0.6814],
         [0.6044, 0.8022],
         [0.3379, 0.6814],
         [0.6044, 0.8022],
         [0.3379, 0.6814]]), torch.Size([6, 2]))

In [288]:
torch.stack([x2,x2,x2]), torch.stack([x2,x2,x2]).shape

(tensor([[[0.6044, 0.8022],
          [0.3379, 0.6814]],
 
         [[0.6044, 0.8022],
          [0.3379, 0.6814]],
 
         [[0.6044, 0.8022],
          [0.3379, 0.6814]]]), torch.Size([3, 2, 2]))

### Interoperating with numpy

In [245]:
t.numpy()

array([[ 0.33151248, -0.02116643,  0.47555122],
       [ 1.432565  , -1.3173373 , -0.19018516],
       [ 1.090355  ,  0.08735733, -0.30689344],
       [ 1.642053  ,  0.7198485 ,  1.0595757 ]], dtype=float32)

In [248]:
a = np.array([1,2,3,4])

In [250]:
tensor(a)

tensor([1, 2, 3, 4])

### Moving objects between devices

In [253]:
t.device

device(type='cpu')

In [ ]:
t.cuda()

In [ ]:
t.device